# Generated by Django 5.1.6 on 2025-03-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Наименование курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
            ],
        ),
    ]
