# Generated by Django 5.1.6 on 2025-03-20 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True, verbose_name='Наименование курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('participants', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Участники курса')),
            ],
        ),
    ]
