# Generated by Django 5.1.6 on 2025-03-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='Наименование урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('additional_materials', models.URLField(blank=True, null=True, verbose_name='Дополнительные материалы')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
        ),
    ]
