# Generated by Django 5.1.6 on 2025-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='deadline',
            new_name='hw_deadline',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='hw_timer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Таймер для ДЗ'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата урока'),
        ),
    ]
