# Generated by Django 5.1.6 on 2025-03-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_rename_deadline_lesson_hw_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='hw_timer',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование урока'),
        ),
    ]
