# Generated by Django 5.1.6 on 2025-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('lesson', '0003_remove_lesson_hw_timer_alter_lesson_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=100, verbose_name='Наименование урока'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'lesson_name'), name='unique_lesson_per_course'),
        ),
    ]
